# Generated by Django 5.0.1 on 2024-01-08 09:36

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=100)),
                ('violation_type', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=dashboard.models.unique_image_path)),
                ('video', models.FileField(upload_to=dashboard.models.unique_video_path)),
                ('camera', models.CharField(max_length=50)),
                ('report', models.FileField(upload_to=dashboard.models.unique_report_path)),
            ],
        ),
    ]
