# Generated by Django 5.0.1 on 2024-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=15)),
                ('owner_name', models.CharField(max_length=100)),
                ('violation_type', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
                ('camera', models.CharField(max_length=50)),
            ],
        ),
    ]
