# Generated by Django 5.0.1 on 2024-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_traffic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
