# Generated by Django 5.0.1 on 2024-01-07 09:13

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_traffic_date_alter_traffic_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='image',
            field=models.ImageField(upload_to=dashboard.models.unique_image_path),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='video',
            field=models.FileField(upload_to=dashboard.models.unique_video_path),
        ),
    ]
